### ISSUE TITLE
add Topic

### ISSUE THREAD

**Issue by alimogh** [ZahraFatehi1378/JelleySeekBar#1]
**درود و سلام**

**میتوانید در بخش**
**About -> Topic**
**را پر کنید تا طرح و پروژه اتان بیشتر دیده شود یا ستاره بخورد**

**همچنین میشود در پروگرس ها هم با تغییراتی بهره گرفت**

**پیروز و سربلند باشید**
**سپاس**

**Comment by ZahraFatehi1378** [comment]
سلام
بله چشم
ممنون از شما

**Comment by ZahraFatehi1378** [comment]
سلام
بله چشم
ممنون از شما
